[package]
name = "densleaf-semantic"
version.workspace = true
edition.workspace = true

[dependencies]
densleaf-ast = { path = "../densleaf-ast" }
densleaf-diagnostic = { path = "../densleaf-diagnostic" }
densleaf-token = { path = "../densleaf-token" }

[lints]
workspace = true

[dev-dependencies]
densleaf-lexer = { path = "../densleaf-lexer" }
densleaf-parser = { path = "../densleaf-parser" }
