use std::fmt::Write;

use densleaf_ast::{Declaration, Expression, Program, Statement};

pub fn generate_rust(program: &Program) -> String {
    let mut output = String::new();
    output.push_str("// Generated by Densleaf. Do not edit by hand.\n\n");
    output.push_str(VALUE_RUNTIME);
    output.push('\n');

    for declaration in &program.declarations {
        match declaration {
            Declaration::Model(model) => {
                writeln!(output, "#[derive(Debug, Clone, PartialEq)]").unwrap();
                writeln!(output, "pub struct {} {{", model.name).unwrap();
                for field in &model.fields {
                    writeln!(
                        output,
                        "    pub {}: {},",
                        field.name,
                        rust_type(&field.type_reference.name)
                    )
                    .unwrap();
                }
                output.push_str("}\n\n");
            }
            Declaration::Controller(controller) => {
                writeln!(output, "pub struct {};", controller.name).unwrap();
                writeln!(output, "\nimpl {} {{", controller.name).unwrap();
                for method in &controller.methods {
                    let mut generic_names = Vec::new();
                    let mut parameters = Vec::new();
                    for (index, parameter) in method.parameters.iter().enumerate() {
                        if let Some(type_reference) = &parameter.type_reference {
                            parameters.push(format!(
                                "{}: {}",
                                parameter.name,
                                rust_type(&type_reference.name)
                            ));
                        } else {
                            let generic = format!("T{index}");
                            generic_names.push(generic.clone());
                            parameters.push(format!("{}: {}", parameter.name, generic));
                        }
                    }
                    let generic_clause = if generic_names.is_empty() {
                        String::new()
                    } else {
                        format!(
                            "<{}>",
                            generic_names
                                .iter()
                                .map(|name| format!("{name}: Into<DensleafValue>"))
                                .collect::<Vec<_>>()
                                .join(", ")
                        )
                    };
                    writeln!(
                        output,
                        "    pub fn {}{}({}) -> DensleafValue {{",
                        method.name,
                        generic_clause,
                        parameters.join(", ")
                    )
                    .unwrap();

                    if method.body.is_empty() {
                        output.push_str("        DensleafValue::Unit\n");
                    } else {
                        for statement in &method.body {
                            match statement {
                                Statement::Return(return_statement) => {
                                    writeln!(
                                        output,
                                        "        return {};",
                                        expression_to_rust(&return_statement.expression)
                                    )
                                    .unwrap();
                                }
                            }
                        }
                        output.push_str("        #[allow(unreachable_code)]\n");
                        output.push_str("        DensleafValue::Unit\n");
                    }
                    output.push_str("    }\n");
                }
                output.push_str("}\n\n");
            }
        }
    }

    output
}

fn rust_type(name: &str) -> &'static str {
    match name {
        "id" | "int" => "i64",
        "bool" => "bool",
        "string" => "String",
        _ => "DensleafValue",
    }
}

fn expression_to_rust(expression: &Expression) -> String {
    match expression {
        Expression::StringLiteral { value, .. } => {
            format!("DensleafValue::String({value:?}.to_string())")
        }
        Expression::IntegerLiteral { value, .. } => format!("DensleafValue::Integer({value})"),
        Expression::BooleanLiteral { value, .. } => format!("DensleafValue::Boolean({value})"),
        Expression::Identifier { name, .. } => format!("{name}.into()"),
    }
}

const VALUE_RUNTIME: &str = r#"#[derive(Debug, Clone, PartialEq)]
pub enum DensleafValue {
    String(String),
    Integer(i64),
    Boolean(bool),
    Unit,
}

impl From<String> for DensleafValue {
    fn from(value: String) -> Self { Self::String(value) }
}

impl From<&str> for DensleafValue {
    fn from(value: &str) -> Self { Self::String(value.to_string()) }
}

impl From<i64> for DensleafValue {
    fn from(value: i64) -> Self { Self::Integer(value) }
}

impl From<bool> for DensleafValue {
    fn from(value: bool) -> Self { Self::Boolean(value) }
}
"#;
