use std::{
    collections::HashSet,
    fmt::Write,
};

use densleaf_ast::{BinaryOperator, Declaration, Expression, Program, Statement, UnaryOperator};

pub fn generate_rust(program: &Program) -> String {
    let globals = program
        .declarations
        .iter()
        .map(|declaration| match declaration {
            Declaration::Model(model) => model.name.clone(),
            Declaration::Controller(controller) => controller.name.clone(),
        })
        .collect::<HashSet<_>>();

    let mut output = String::new();
    output.push_str("// Generated by Densleaf. Do not edit by hand.\n\n");
    output.push_str(VALUE_RUNTIME);
    output.push('\n');

    for declaration in &program.declarations {
        match declaration {
            Declaration::Model(model) => {
                writeln!(output, "#[derive(Debug, Clone, PartialEq)]").unwrap();
                writeln!(output, "pub struct {} {{", model.name).unwrap();
                for field in &model.fields {
                    writeln!(
                        output,
                        "    pub {}: {},",
                        field.name,
                        rust_type(&field.type_reference.name)
                    )
                    .unwrap();
                }
                output.push_str("}\n\n");
            }
            Declaration::Controller(controller) => {
                writeln!(output, "pub struct {};", controller.name).unwrap();
                writeln!(output, "\nimpl {} {{", controller.name).unwrap();

                for method in &controller.methods {
                    let mut generic_names = Vec::new();
                    let mut parameters = Vec::new();
                    let mut bindings = HashSet::new();

                    for (index, parameter) in method.parameters.iter().enumerate() {
                        bindings.insert(parameter.name.clone());

                        if let Some(type_reference) = &parameter.type_reference {
                            parameters.push(format!(
                                "{}: {}",
                                parameter.name,
                                rust_type(&type_reference.name)
                            ));
                        } else {
                            let generic = format!("T{index}");
                            generic_names.push(generic.clone());
                            parameters.push(format!("{}: {}", parameter.name, generic));
                        }
                    }

                    let generic_clause = if generic_names.is_empty() {
                        String::new()
                    } else {
                        format!(
                            "<{}>",
                            generic_names
                                .iter()
                                .map(|name| format!("{name}: Clone + Into<DensleafValue>"))
                                .collect::<Vec<_>>()
                                .join(", ")
                        )
                    };

                    writeln!(
                        output,
                        "    pub fn {}{}({}) -> DensleafValue {{",
                        method.name,
                        generic_clause,
                        parameters.join(", ")
                    )
                    .unwrap();

                    if method.body.is_empty() {
                        output.push_str("        DensleafValue::Unit\n");
                    } else {
                        for statement in &method.body {
                            match statement {
                                Statement::Let(let_statement) => {
                                    writeln!(
                                        output,
                                        "        let {}: DensleafValue = {};",
                                        let_statement.name,
                                        expression_to_rust(
                                            &let_statement.initializer,
                                            &globals,
                                            &bindings,
                                        )
                                    )
                                    .unwrap();
                                    bindings.insert(let_statement.name.clone());
                                }
                                Statement::Return(return_statement) => {
                                    writeln!(
                                        output,
                                        "        return {};",
                                        expression_to_rust(
                                            &return_statement.expression,
                                            &globals,
                                            &bindings,
                                        )
                                    )
                                    .unwrap();
                                }
                            }
                        }

                        output.push_str("        #[allow(unreachable_code)]\n");
                        output.push_str("        DensleafValue::Unit\n");
                    }

                    output.push_str("    }\n");
                }

                output.push_str("}\n\n");
            }
        }
    }

    output
}

fn rust_type(name: &str) -> &'static str {
    match name {
        "id" | "int" => "i64",
        "bool" => "bool",
        "string" => "String",
        _ => "DensleafValue",
    }
}

fn expression_to_rust(
    expression: &Expression,
    globals: &HashSet<String>,
    bindings: &HashSet<String>,
) -> String {
    match expression {
        Expression::StringLiteral { value, .. } => {
            format!("DensleafValue::String({value:?}.to_string())")
        }
        Expression::IntegerLiteral { value, .. } => format!("DensleafValue::Integer({value})"),
        Expression::BooleanLiteral { value, .. } => format!("DensleafValue::Boolean({value})"),
        Expression::NullLiteral { .. } => "DensleafValue::Null".to_string(),
        Expression::Identifier { name, .. } if bindings.contains(name) => {
            format!("{name}.clone().into()")
        }
        Expression::Identifier { name, .. } if globals.contains(name) => {
            format!("DensleafValue::Type({name:?}.to_string())")
        }
        Expression::Identifier { name, .. } => format!("{name}.clone().into()"),
        Expression::ArrayLiteral { elements, .. } => {
            let elements = elements
                .iter()
                .map(|element| expression_to_rust(element, globals, bindings))
                .collect::<Vec<_>>()
                .join(", ");
            format!("DensleafValue::Array(vec![{elements}])")
        }
        Expression::ObjectLiteral { entries, .. } => {
            let entries = entries
                .iter()
                .map(|entry| {
                    format!(
                        "({:?}.to_string(), {})",
                        entry.key,
                        expression_to_rust(&entry.value, globals, bindings)
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("DensleafValue::Object(vec![{entries}])")
        }
        Expression::Grouped { expression, .. } => {
            format!("({})", expression_to_rust(expression, globals, bindings))
        }
        Expression::Unary {
            operator, operand, ..
        } => {
            let operand = expression_to_rust(operand, globals, bindings);
            match operator {
                UnaryOperator::Not => format!("densleaf_not({operand})"),
                UnaryOperator::Negate => format!("densleaf_negate({operand})"),
            }
        }
        Expression::Binary {
            left,
            operator,
            right,
            ..
        } => {
            let left = expression_to_rust(left, globals, bindings);
            let right = expression_to_rust(right, globals, bindings);
            match operator {
                BinaryOperator::Add => format!("densleaf_add({left}, {right})"),
                BinaryOperator::Subtract => format!("densleaf_subtract({left}, {right})"),
                BinaryOperator::Multiply => format!("densleaf_multiply({left}, {right})"),
                BinaryOperator::Divide => format!("densleaf_divide({left}, {right})"),
                BinaryOperator::Remainder => format!("densleaf_remainder({left}, {right})"),
                BinaryOperator::Equal => format!("densleaf_equal({left}, {right})"),
                BinaryOperator::NotEqual => format!("densleaf_not_equal({left}, {right})"),
                BinaryOperator::Less => format!("densleaf_less({left}, {right})"),
                BinaryOperator::LessEqual => format!("densleaf_less_equal({left}, {right})"),
                BinaryOperator::Greater => format!("densleaf_greater({left}, {right})"),
                BinaryOperator::GreaterEqual => format!("densleaf_greater_equal({left}, {right})"),
                BinaryOperator::And => format!("densleaf_and({left}, || {right})"),
                BinaryOperator::Or => format!("densleaf_or({left}, || {right})"),
            }
        }
        Expression::MemberAccess { object, member, .. } => format!(
            "densleaf_get_member({}, {:?})",
            expression_to_rust(object, globals, bindings),
            member
        ),
        Expression::Call {
            callee, arguments, ..
        } => {
            let arguments = arguments
                .iter()
                .map(|argument| expression_to_rust(argument, globals, bindings))
                .collect::<Vec<_>>()
                .join(", ");

            if let Expression::MemberAccess { object, member, .. } = callee.as_ref() {
                format!(
                    "densleaf_call_member({}, {:?}, vec![{}])",
                    expression_to_rust(object, globals, bindings),
                    member,
                    arguments
                )
            } else {
                format!(
                    "densleaf_call({}, vec![{}])",
                    expression_to_rust(callee, globals, bindings),
                    arguments
                )
            }
        }
        Expression::Index { object, index, .. } => format!(
            "densleaf_index({}, {})",
            expression_to_rust(object, globals, bindings),
            expression_to_rust(index, globals, bindings)
        ),
    }
}

const VALUE_RUNTIME: &str = r#"#[derive(Debug, Clone, PartialEq)]
pub enum DensleafValue {
    String(String),
    Integer(i64),
    Boolean(bool),
    Null,
    Array(Vec<DensleafValue>),
    Object(Vec<(String, DensleafValue)>),
    Type(String),
    Member {
        target: Box<DensleafValue>,
        name: String,
    },
    Unit,
}

impl From<String> for DensleafValue {
    fn from(value: String) -> Self { Self::String(value) }
}

impl From<&str> for DensleafValue {
    fn from(value: &str) -> Self { Self::String(value.to_string()) }
}

impl From<i64> for DensleafValue {
    fn from(value: i64) -> Self { Self::Integer(value) }
}

impl From<bool> for DensleafValue {
    fn from(value: bool) -> Self { Self::Boolean(value) }
}

fn densleaf_not(value: DensleafValue) -> DensleafValue {
    match value {
        DensleafValue::Boolean(value) => DensleafValue::Boolean(!value),
        other => panic!("Densleaf `!` expects bool, received {other:?}"),
    }
}

fn densleaf_negate(value: DensleafValue) -> DensleafValue {
    match value {
        DensleafValue::Integer(value) => DensleafValue::Integer(
            value.checked_neg().expect("Densleaf integer negation overflow"),
        ),
        other => panic!("Densleaf unary `-` expects int, received {other:?}"),
    }
}

fn densleaf_add(left: DensleafValue, right: DensleafValue) -> DensleafValue {
    match (left, right) {
        (DensleafValue::Integer(left), DensleafValue::Integer(right)) => {
            DensleafValue::Integer(
                left.checked_add(right)
                    .expect("Densleaf integer addition overflow"),
            )
        }
        (DensleafValue::String(mut left), DensleafValue::String(right)) => {
            left.push_str(&right);
            DensleafValue::String(left)
        }
        (left, right) => panic!(
            "Densleaf `+` expects int + int or string + string, received {left:?} and {right:?}"
        ),
    }
}

fn densleaf_subtract(left: DensleafValue, right: DensleafValue) -> DensleafValue {
    match (left, right) {
        (DensleafValue::Integer(left), DensleafValue::Integer(right)) => {
            DensleafValue::Integer(
                left.checked_sub(right)
                    .expect("Densleaf integer subtraction overflow"),
            )
        }
        (left, right) => {
            panic!("Densleaf `-` expects int - int, received {left:?} and {right:?}")
        }
    }
}

fn densleaf_multiply(left: DensleafValue, right: DensleafValue) -> DensleafValue {
    match (left, right) {
        (DensleafValue::Integer(left), DensleafValue::Integer(right)) => {
            DensleafValue::Integer(
                left.checked_mul(right)
                    .expect("Densleaf integer multiplication overflow"),
            )
        }
        (left, right) => {
            panic!("Densleaf `*` expects int * int, received {left:?} and {right:?}")
        }
    }
}

fn densleaf_divide(left: DensleafValue, right: DensleafValue) -> DensleafValue {
    match (left, right) {
        (DensleafValue::Integer(left), DensleafValue::Integer(right)) => {
            DensleafValue::Integer(
                left.checked_div(right)
                    .expect("Densleaf integer division overflow or division by zero"),
            )
        }
        (left, right) => {
            panic!("Densleaf `/` expects int / int, received {left:?} and {right:?}")
        }
    }
}

fn densleaf_remainder(left: DensleafValue, right: DensleafValue) -> DensleafValue {
    match (left, right) {
        (DensleafValue::Integer(left), DensleafValue::Integer(right)) => {
            DensleafValue::Integer(
                left.checked_rem(right)
                    .expect("Densleaf integer remainder overflow or division by zero"),
            )
        }
        (left, right) => {
            panic!("Densleaf `%` expects int % int, received {left:?} and {right:?}")
        }
    }
}

fn densleaf_equal(left: DensleafValue, right: DensleafValue) -> DensleafValue {
    DensleafValue::Boolean(left == right)
}

fn densleaf_not_equal(left: DensleafValue, right: DensleafValue) -> DensleafValue {
    DensleafValue::Boolean(left != right)
}

fn densleaf_less(left: DensleafValue, right: DensleafValue) -> DensleafValue {
    densleaf_compare(left, right, |ordering| ordering.is_lt(), "<")
}

fn densleaf_less_equal(left: DensleafValue, right: DensleafValue) -> DensleafValue {
    densleaf_compare(left, right, |ordering| ordering.is_le(), "<=")
}

fn densleaf_greater(left: DensleafValue, right: DensleafValue) -> DensleafValue {
    densleaf_compare(left, right, |ordering| ordering.is_gt(), ">")
}

fn densleaf_greater_equal(left: DensleafValue, right: DensleafValue) -> DensleafValue {
    densleaf_compare(left, right, |ordering| ordering.is_ge(), ">=")
}

fn densleaf_compare(
    left: DensleafValue,
    right: DensleafValue,
    compare: impl FnOnce(std::cmp::Ordering) -> bool,
    operator: &str,
) -> DensleafValue {
    let ordering = match (left, right) {
        (DensleafValue::Integer(left), DensleafValue::Integer(right)) => left.cmp(&right),
        (DensleafValue::String(left), DensleafValue::String(right)) => left.cmp(&right),
        (left, right) => panic!(
            "Densleaf `{operator}` expects matching int or string values, received {left:?} and {right:?}"
        ),
    };
    DensleafValue::Boolean(compare(ordering))
}

fn densleaf_and(
    left: DensleafValue,
    right: impl FnOnce() -> DensleafValue,
) -> DensleafValue {
    match left {
        DensleafValue::Boolean(false) => DensleafValue::Boolean(false),
        DensleafValue::Boolean(true) => match right() {
            DensleafValue::Boolean(value) => DensleafValue::Boolean(value),
            other => panic!("Densleaf `&&` expects bool operands, received {other:?}"),
        },
        other => panic!("Densleaf `&&` expects bool operands, received {other:?}"),
    }
}

fn densleaf_or(
    left: DensleafValue,
    right: impl FnOnce() -> DensleafValue,
) -> DensleafValue {
    match left {
        DensleafValue::Boolean(true) => DensleafValue::Boolean(true),
        DensleafValue::Boolean(false) => match right() {
            DensleafValue::Boolean(value) => DensleafValue::Boolean(value),
            other => panic!("Densleaf `||` expects bool operands, received {other:?}"),
        },
        other => panic!("Densleaf `||` expects bool operands, received {other:?}"),
    }
}

fn densleaf_get_member(value: DensleafValue, member: &str) -> DensleafValue {
    match value {
        DensleafValue::Object(entries) => entries
            .into_iter()
            .find_map(|(key, value)| (key == member).then_some(value))
            .unwrap_or_else(|| panic!("Densleaf object has no member `{member}`")),
        DensleafValue::Type(name) => DensleafValue::Member {
            target: Box::new(DensleafValue::Type(name)),
            name: member.to_string(),
        },
        other => panic!("Densleaf member access is not supported on {other:?}"),
    }
}

fn densleaf_call(callee: DensleafValue, arguments: Vec<DensleafValue>) -> DensleafValue {
    match callee {
        DensleafValue::Member { target, name } => {
            densleaf_call_member(*target, &name, arguments)
        }
        other => panic!("Densleaf value is not callable: {other:?}"),
    }
}

fn densleaf_call_member(
    target: DensleafValue,
    member: &str,
    arguments: Vec<DensleafValue>,
) -> DensleafValue {
    let _ = arguments;
    panic!("Densleaf runtime call `{member}` is not implemented for {target:?}")
}

fn densleaf_index(value: DensleafValue, index: DensleafValue) -> DensleafValue {
    match (value, index) {
        (DensleafValue::Array(values), DensleafValue::Integer(index)) => {
            if index < 0 {
                panic!("Densleaf array index cannot be negative: {index}");
            }
            values
                .get(index as usize)
                .cloned()
                .unwrap_or_else(|| panic!("Densleaf array index out of bounds: {index}"))
        }
        (DensleafValue::Object(entries), DensleafValue::String(index)) => entries
            .into_iter()
            .find_map(|(key, value)| (key == index).then_some(value))
            .unwrap_or_else(|| panic!("Densleaf object has no key `{index}`")),
        (value, index) => {
            panic!("Densleaf indexing is not supported for {value:?} with index {index:?}")
        }
    }
}
"#;
