name: CI

on:
  push:
    branches: [main, "foundation/**", "feature/**"]
  pull_request:

jobs:
  compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal --component rustfmt,clippy
          rustup default stable
      - name: Format
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Test
        run: cargo test --workspace
      - name: Check reference application
        run: cargo run -p densleaf-cli -- check examples/hello/app.dl
      - name: Generate reference application
        run: cargo run -p densleaf-cli -- build examples/hello/app.dl
      - name: Compile generated reference Rust
        run: rustc --edition 2024 --crate-type lib .densleaf/generated/app.rs -o /tmp/libdensleaf_generated.rlib
      - name: Check core expression application
        run: cargo run -p densleaf-cli -- check examples/core-expressions/expressions.dl
      - name: Generate core expression application
        run: cargo run -p densleaf-cli -- build examples/core-expressions/expressions.dl
      - name: Compile generated core expression Rust
        run: rustc --edition 2024 --crate-type lib .densleaf/generated/expressions.rs -o /tmp/libdensleaf_expressions.rlib

      - name: Check application declaration grammar
        run: cargo run -p densleaf-cli -- check examples/application-declarations/app.dl
      - name: Generate application declaration Rust
        run: cargo run -p densleaf-cli -- build examples/application-declarations/app.dl
      - name: Compile generated application declaration Rust
        run: rustc --edition 2024 --crate-type lib .densleaf/generated/app.rs -o /tmp/libdensleaf_app_declarations.rlib

      - name: Check messaging declaration grammar
        run: cargo run -p densleaf-cli -- check examples/messaging/messaging.dl
      - name: Generate messaging declaration Rust
        run: cargo run -p densleaf-cli -- build examples/messaging/messaging.dl
      - name: Compile generated messaging declaration Rust
        run: rustc --edition 2024 --crate-type lib .densleaf/generated/messaging.rs -o /tmp/libdensleaf_messaging.rlib
